apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-helloworld
  template:
    metadata:
      labels:
        app: spring-helloworld
    spec:
      containers:
      - name: spring-helloworld
        image: cloudmonster123/spring-boot-app-k8s-deployment:v17
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 8081

